/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './message-input.component.ngfactory';
import * as import2 from './message-input.component';
import * as import3 from './message.service';
import * as import4 from './message-list.component.ngfactory';
import * as import5 from './message-list.component';
import * as import6 from './messages.component';
const styles_MessagesComponent:any[] = ([] as any[]);
export const RenderType_MessagesComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_MessagesComponent,
  data: {}
}
);
export function View_MessagesComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵted((null as any),['\n        '])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),4,'div',[[
        'class',
        'row'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n            '])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'app-message-input',([] as any[]),(null as any),(null as any),(null as any),import1.View_MessageInputComponent_0,import1.RenderType_MessageInputComponent)),
    import0.ɵdid(114688,(null as any),0,import2.MessageInputComponent,[import3.MessageService],(null as any),(null as any)),
    (l()(),import0.ɵted((null as any),['\n        '])),
    (l()(),import0.ɵted((null as any),['\n        '])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),0,'br',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n        '])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),4,'div',[[
        'class',
        'row'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n            '])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'app-message-list',([] as any[]),(null as any),(null as any),(null as any),import4.View_MessageListComponent_0,import4.RenderType_MessageListComponent)),
    import0.ɵdid(114688,(null as any),0,import5.MessageListComponent,[import3.MessageService],(null as any),(null as any)),
    (l()(),import0.ɵted((null as any),['\n        '])),
    (l()(),import0.ɵted((null as any),['\n    ']))
  ]
  ,(ck,v) => {
    ck(v,4,0);
    ck(v,12,0);
  },(null as any));
}
function View_MessagesComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'app-messages',([] as any[]),(null as any),(null as any),(null as any),View_MessagesComponent_0,RenderType_MessagesComponent)),
    import0.ɵdid(49152,(null as any),0,import6.MessagesComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const MessagesComponentNgFactory:import0.ComponentFactory<import6.MessagesComponent> = import0.ɵccf('app-messages',import6.MessagesComponent,View_MessagesComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvYmVuYmEvT25lRHJpdmUvRGV2L0RvemVyYW5kU2NobWl0dC9uZXctY291cnNlL2Fzc2V0cy9hcHAvbWVzc2FnZXMvbWVzc2FnZXMuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL2JlbmJhL09uZURyaXZlL0Rldi9Eb3plcmFuZFNjaG1pdHQvbmV3LWNvdXJzZS9hc3NldHMvYXBwL21lc3NhZ2VzL21lc3NhZ2VzLmNvbXBvbmVudC50cyIsIm5nOi8vL0M6L1VzZXJzL2JlbmJhL09uZURyaXZlL0Rldi9Eb3plcmFuZFNjaG1pdHQvbmV3LWNvdXJzZS9hc3NldHMvYXBwL21lc3NhZ2VzL21lc3NhZ2VzLmNvbXBvbmVudC50cy5NZXNzYWdlc0NvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvYmVuYmEvT25lRHJpdmUvRGV2L0RvemVyYW5kU2NobWl0dC9uZXctY291cnNlL2Fzc2V0cy9hcHAvbWVzc2FnZXMvbWVzc2FnZXMuY29tcG9uZW50LnRzLk1lc3NhZ2VzQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiXG4gICAgICAgIDxkaXYgY2xhc3M9XCJyb3dcIj5cbiAgICAgICAgICAgIDxhcHAtbWVzc2FnZS1pbnB1dD48L2FwcC1tZXNzYWdlLWlucHV0PlxuICAgICAgICA8L2Rpdj5cbiAgICAgICAgPGJyPlxuICAgICAgICA8ZGl2IGNsYXNzPVwicm93XCI+XG4gICAgICAgICAgICA8YXBwLW1lc3NhZ2UtbGlzdD48L2FwcC1tZXNzYWdlLWxpc3Q+XG4gICAgICAgIDwvZGl2PlxuICAgICIsIjxhcHAtbWVzc2FnZXM+PC9hcHAtbWVzc2FnZXM+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O0lDQUE7TUFDUTtRQUFBO1FBQUE7TUFBQTtJQUFBO0lBQWlCO0lBQ2I7Z0JBQUE7SUFBdUM7SUFDckM7SUFDTjtJQUFJO01BQ0o7UUFBQTtRQUFBO01BQUE7SUFBQTtJQUFpQjtJQUNiO2dCQUFBO0lBQXFDO0lBQ25DOzs7SUFMRjtJQUlBOzs7OztJQ05aO2dCQUFBOzs7OyJ9
